-- DropForeignKey
ALTER TABLE "Question" DROP CONSTRAINT "Question_FK_ID_SURVEY_fkey";

-- AddForeignKey
ALTER TABLE "Question" ADD CONSTRAINT "Question_FK_ID_SURVEY_fkey" FOREIGN KEY ("FK_ID_SURVEY") REFERENCES "Survey"("ID_SURVEY") ON DELETE CASCADE ON UPDATE CASCADE;
